"use client";
import { useEffect, useState } from "react";
import { getSessionContext } from "../../lib/app-data";
type Customer={id:string;name:string;phone:string;notes:string;archived:boolean};
export default function CustomersPage(){const [rows,setRows]=useState<Customer[]>([]);const [name,setName]=useState("");const [phone,setPhone]=useState("");const [notes,setNotes]=useState("");const [query,setQuery]=useState("");const [message,setMessage]=useState("");const [loading,setLoading]=useState(true);
async function load(){try{const {supabase,teamId}=await getSessionContext();const {data,error}=await supabase.from("customers").select("id,name,phone,notes,archived").eq("team_id",teamId).eq("archived",false).order("name");if(error)throw error;setRows((data??[]) as Customer[])}catch(e){setMessage(e instanceof Error?e.message:"No pudimos cargar tus clientes.")}finally{setLoading(false)}}useEffect(()=>{load()},[]);
async function add(e:React.FormEvent){e.preventDefault();try{const {supabase,user,teamId}=await getSessionContext();const {error}=await supabase.from("customers").insert({team_id:teamId,owner_user_id:user.id,name:name.trim(),phone:phone.trim(),notes:notes.trim()});if(error)throw error;setName("");setPhone("");setNotes("");setMessage("Cliente guardado.");await load()}catch(e){setMessage(e instanceof Error?e.message:"No pudimos guardar el cliente.")}}
async function archive(id:string){const {supabase}=await getSessionContext();await supabase.from("customers").update({archived:true}).eq("id",id);await load()}
const visible=rows.filter(r=>(r.name+" "+r.phone).toLowerCase().includes(query.toLowerCase()));return <main><section className="hero"><p className="eyebrow">VV / Relaciones</p><h1>Cada contacto cuenta.</h1><p className="lede">Organiza tus clientes y prepara tu próxima visita desde cualquier dispositivo.</p></section>{message&&<div className="notice" role="status">{message}</div>}<section className="card"><h2>Nuevo cliente</h2><form onSubmit={add} className="form-grid"><label>Nombre<input required value={name} onChange={e=>setName(e.target.value)}/></label><label>Teléfono / WhatsApp<input required inputMode="tel" value={phone} onChange={e=>setPhone(e.target.value)}/></label><label className="full">Notas<textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Preferencias o instrucciones de entrega"/></label><button className="full" type="submit">Guardar cliente</button></form></section><div className="section-head"><h2>Tus clientes ({visible.length})</h2><input style={{maxWidth:260}} placeholder="Buscar" value={query} onChange={e=>setQuery(e.target.value)}/></div>{loading?<div className="state card"><div className="spinner"/><p>Cargando clientes…</p></div>:visible.length===0?<div className="state card"><h2>Aún no tienes clientes</h2><p className="muted">Añade tu primer contacto para asociarlo a un pedido.</p></div>:<section className="list">{visible.map(c=><article className="list-row" key={c.id}><div><strong>{c.name}</strong><p className="muted">{c.phone}</p>{c.notes&&<p>{c.notes}</p>}</div><div style={{display:"flex",gap:8,flexWrap:"wrap"}}><a className="button secondary" href={"https://wa.me/"+c.phone.replace(/[^0-9]/g,"")} target="_blank" rel="noreferrer">WhatsApp</a><button className="button ghost" onClick={()=>archive(c.id)}>Archivar</button></div></article>)}</section>}</main>}
