"use client";
import Link from "next/link";
import { useEffect,useMemo,useState } from "react";
import { createClient } from "../../lib/supabase";
import { getSessionContext } from "../../lib/app-data";
import viveCatalog from "../../data/vive_catalog.json";
type Product={id:string;slug:string;name:string;description:string|null;category:string|null;price_cents:number;currency:string;available:boolean;image_url:string|null};
const officialBySlug=new Map(viveCatalog.map(item=>[item.slug,item]));
export default function CatalogPage(){const [products,setProducts]=useState<Product[]>([]);const [query,setQuery]=useState("");const [category,setCategory]=useState("Todas");const [loading,setLoading]=useState(true);const [error,setError]=useState("");
useEffect(()=>{let active=true;(async()=>{try{const {data,error:e}=await createClient().from("products").select("id,slug,name,description,category,price_cents,currency,available,image_url").order("name");if(e)throw e;if(active)setProducts((data??[]).map(p=>{const official=officialBySlug.get(p.slug);return {...p,description:p.description||official?.description||null,image_url:p.image_url||official?.image_urls?.[0]||null}}) as Product[])}catch(e){if(active)setError(e instanceof Error?e.message:"No se pudo cargar el catálogo.")}finally{if(active)setLoading(false)}})();return()=>{active=false}},[]);
const categories=useMemo(()=>["Todas",...Array.from(new Set(products.map(p=>p.category).filter(Boolean) as string[]))],[products]);const visible=products.filter(p=>(category==="Todas"||p.category===category)&&(p.name+" "+(p.category??"")).toLowerCase().includes(query.toLowerCase()));
async function addToCart(productId:string){try{const {supabase,user,teamId}=await getSessionContext();let {data:cart}=await supabase.from("carts").select("id").eq("user_id",user.id).eq("team_id",teamId).eq("status","ACTIVE").maybeSingle();if(!cart){const created=await supabase.from("carts").insert({user_id:user.id,team_id:teamId}).select("id").single();if(created.error)throw created.error;cart=created.data}const existing=await supabase.from("cart_items").select("quantity").eq("cart_id",cart.id).eq("product_id",productId).maybeSingle();const result=existing.data?await supabase.from("cart_items").update({quantity:existing.data.quantity+1}).eq("cart_id",cart.id).eq("product_id",productId):await supabase.from("cart_items").insert({cart_id:cart.id,product_id:productId,quantity:1});if(result.error)throw result.error;alert("Producto añadido al carrito.")}catch(e){alert(e instanceof Error?e.message:"No pudimos añadir el producto.")}}
return <main><section className="hero hero-grid"><div><p className="eyebrow">VV / Colecciones</p><h1>Encuentra tu próxima venta.</h1><p className="lede">Explora productos, comparte fichas y prepara pedidos en segundos.</p></div><div className="hero-stat"><strong>{products.length}</strong><span>productos disponibles</span></div></section><section className="toolbar"><label className="search"><span className="sr-only">Buscar productos</span><input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar por nombre o categoría"/></label><select value={category} onChange={e=>setCategory(e.target.value)} aria-label="Categoría">{categories.map(c=><option key={c}>{c}</option>)}</select></section>{loading?<div className="state card"><div className="spinner"/><p>Cargando catálogo…</p></div>:error?<div className="state card"><h2>No pudimos cargar el catálogo</h2><p>{error}</p><button onClick={()=>location.reload()}>Reintentar</button></div>:visible.length===0?<div className="state card"><h2>No encontramos productos</h2><p className="muted">Prueba otra búsqueda o categoría.</p></div>:<section className="grid" aria-label="Productos">{visible.map(p=><article className="product-card" key={p.id}><div className="product-image">{p.image_url?<img src={p.image_url} alt={p.name} loading="lazy"/>:<span>{p.name.slice(0,1)}</span>}</div><div className="product-content"><span className="badge">{p.category??"Sin categoría"}</span><h2>{p.name}</h2><p className="product-description">{p.description??"Descripción disponible en la ficha."}</p><strong>{p.price_cents?`${p.currency} ${(p.price_cents/100).toFixed(2)}`:"Precio por confirmar"}</strong><div style={{display:"flex",gap:8,flexWrap:"wrap"}}><Link className="button secondary" href={"/catalogo/"+p.slug}>Ver ficha</Link><button onClick={()=>addToCart(p.id)}>Añadir</button></div></div></article>)}</section>}</main>}
