"use client";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { createClient } from "../../lib/supabase";
 type Product = { id: string; slug: string; name: string; category: string | null; price_cents: number; currency: string; available: boolean };
export default function CatalogPage(){
 const [products,setProducts]=useState<Product[]>([]),[query,setQuery]=useState(""),[category,setCategory]=useState("Todas"),[loading,setLoading]=useState(true),[error,setError]=useState("");
 useEffect(()=>{let active=true; (async()=>{try{const {data,error:e}=await createClient().from("products").select("id,slug,name,category,price_cents,currency,available").order("name");if(e)throw e;if(active)setProducts((data??[]) as Product[]);}catch(e){if(active)setError(e instanceof Error?e.message:"No se pudo cargar el catálogo.");}finally{if(active)setLoading(false);}})();return()=>{active=false};},[]);
 const categories=useMemo(()=>["Todas",...Array.from(new Set(products.map(p=>p.category).filter(Boolean) as string[]))],[products]);
 const visible=products.filter(p=>(category==="Todas"||p.category===category)&&`${p.name} ${p.category??""}`.toLowerCase().includes(query.toLowerCase()));
 return <><section className="hero hero-grid"><div><p className="eyebrow">Catálogo privado por equipo</p><h1>Vende con claridad.</h1><p className="lede">Encuentra productos disponibles, comparte una ficha y arma tu pedido en segundos.</p></div><div className="hero-stat"><strong>{products.length}</strong><span>productos en la campaña</span></div></section><section className="toolbar" aria-label="Filtros del catálogo"><label className="search"><span className="sr-only">Buscar productos</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar por nombre o categoría" type="search" /></label><label><span className="sr-only">Filtrar por categoría</span><select value={category} onChange={e=>setCategory(e.target.value)}>{categories.map(item=><option key={item}>{item}</option>)}</select></label></section>{loading&&<div className="state card"><div className="spinner" aria-hidden="true"/><p>Cargando productos…</p></div>}{!loading&&error&&<div className="state card"><h2>No pudimos cargar el catálogo</h2><p className="muted">Configura la conexión de Supabase o inténtalo de nuevo.</p><code>{error}</code></div>}{!loading&&!error&&visible.length===0&&<div className="state card"><h2>Aún no hay productos para mostrar</h2><p className="muted">Cuando el equipo publique una campaña, aparecerá aquí.</p><Link className="button secondary" href="/admin/catalogo">Ir a importar catálogo</Link></div>}{!loading&&!error&&visible.length>0&&<section className="grid" aria-label="Productos">{visible.map(p=><article className="product-card" key={p.id}><div className="product-image" aria-hidden="true">{p.name.slice(0,1)}</div><div className="product-content"><p className="muted">{p.category??"Sin categoría"}</p><h2>{p.name}</h2><strong>{Number(p.price_cents)>0?`${p.currency} ${(Number(p.price_cents)/100).toFixed(2)}`:"Precio por confirmar"}</strong><Link className="button secondary" href={`/catalogo/${p.slug}`}>Ver ficha</Link></div></article>)}</section>}</>;
}
