"use client";
import Link from "next/link";
import { useEffect,useState } from "react";
import { useParams } from "next/navigation";
import { createClient } from "../../../lib/supabase";
import { getSessionContext,money } from "../../../lib/app-data";
type Product={id:string;slug:string;name:string;description:string;category:string;price_cents:number;currency:string;available:boolean;image_url:string|null};
export default function ProductPage(){const params=useParams<{slug:string}>();const [product,setProduct]=useState<Product|null>(null);const [error,setError]=useState("");const [busy,setBusy]=useState(false);useEffect(()=>{(async()=>{const {data,error:e}=await createClient().from("products").select("id,slug,name,description,category,price_cents,currency,available,image_url").eq("slug",params.slug).maybeSingle();if(e)setError(e.message);else setProduct(data as Product|null)})()},[params.slug]);
async function add(){if(!product)return;setBusy(true);try{const {supabase,user,teamId}=await getSessionContext();let {data:cart}=await supabase.from("carts").select("id").eq("user_id",user.id).eq("team_id",teamId).eq("status","ACTIVE").maybeSingle();if(!cart){const created=await supabase.from("carts").insert({user_id:user.id,team_id:teamId}).select("id").single();if(created.error)throw created.error;cart=created.data}const result=await supabase.from("cart_items").upsert({cart_id:cart.id,product_id:product.id,quantity:1},{onConflict:"cart_id,product_id"});if(result.error)throw result.error;setError("Producto añadido al carrito.")}catch(e){setError(e instanceof Error?e.message:"No pudimos añadir el producto.")}finally{setBusy(false)}}if(error&&!product)return <main><div className="state card"><h2>Producto no encontrado</h2><p>{error}</p><Link className="button" href="/catalogo">Volver al catálogo</Link></div></main>;if(!product)return <main><div className="state card"><div className="spinner"/><p>Cargando ficha…</p></div></main>;return <main><article className="card product-detail"><div className="detail-image">{product.image_url?<img src={product.image_url} alt={product.name}/>:<span>{product.name.slice(0,1)}</span>}</div><span className="badge">{product.category}</span><h1>{product.name}</h1><p className="product-description detail-description">{product.description||"Descripción disponible en la ficha del producto."}</p><strong>{product.price_cents?money(product.price_cents,product.currency):"Precio por confirmar"}</strong><p className="muted">{product.available?"Disponible para pedido":"Producto no disponible"}</p>{error&&<p className="notice" role="status">{error}</p>}<button disabled={!product.available||busy} onClick={add}>{busy?"Añadiendo…":"Añadir al carrito"}</button><p><Link href="/catalogo">← Volver al catálogo</Link></p></article></main>}
